spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spring_app?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages/messages,messages/validationMessages